[package]
name = "homespaces"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.1.3"
winreg = "0.52.0"

[dependencies.windows]
version = "0.54.0"
features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging"
]
